baseurl = "http://radioquotes.xyz/"
title = "Radio Quotes"
author = "Maksim Z."
canonifyurls = true

DefaultContentLanguage = "ru"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Radio Quotes"
  disableWebFonts = false

# [[menu.main]]
#     name = "About"
#     url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
# [[menu.main]]
#     name = "Projects"
#     url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
# [[menu.main]]
#     name = "Resume"
#     url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
