name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'

      - name: Buld static
        run: hugo --minify

      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: radioquotes
          path: public
